// Code generated by protoc-gen-go.
// source: process/protoprocess.proto
// DO NOT EDIT!

/*
Package protoprocess is a generated protocol buffer package.

It is generated from these files:
	process/protoprocess.proto

It has these top-level messages:
*/
package protoprocess

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "go.pedge.io/pb/go/google/protobuf"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for API service

type APIClient interface {
	Do(ctx context.Context, opts ...grpc.CallOption) (API_DoClient, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) Do(ctx context.Context, opts ...grpc.CallOption) (API_DoClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_API_serviceDesc.Streams[0], c.cc, "/protoprocess.API/Do", opts...)
	if err != nil {
		return nil, err
	}
	x := &aPIDoClient{stream}
	return x, nil
}

type API_DoClient interface {
	Send(*google_protobuf.BytesValue) error
	Recv() (*google_protobuf.BytesValue, error)
	grpc.ClientStream
}

type aPIDoClient struct {
	grpc.ClientStream
}

func (x *aPIDoClient) Send(m *google_protobuf.BytesValue) error {
	return x.ClientStream.SendMsg(m)
}

func (x *aPIDoClient) Recv() (*google_protobuf.BytesValue, error) {
	m := new(google_protobuf.BytesValue)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for API service

type APIServer interface {
	Do(API_DoServer) error
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_Do_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(APIServer).Do(&aPIDoServer{stream})
}

type API_DoServer interface {
	Send(*google_protobuf.BytesValue) error
	Recv() (*google_protobuf.BytesValue, error)
	grpc.ServerStream
}

type aPIDoServer struct {
	grpc.ServerStream
}

func (x *aPIDoServer) Send(m *google_protobuf.BytesValue) error {
	return x.ServerStream.SendMsg(m)
}

func (x *aPIDoServer) Recv() (*google_protobuf.BytesValue, error) {
	m := new(google_protobuf.BytesValue)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protoprocess.API",
	HandlerType: (*APIServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Do",
			Handler:       _API_Do_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "process/protoprocess.proto",
}

func init() { proto.RegisterFile("process/protoprocess.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 117 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x28, 0xca, 0x4f,
	0x4e, 0x2d, 0x2e, 0xd6, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x87, 0x72, 0xf4, 0xc0, 0x1c, 0x21, 0x1e,
	0x64, 0x31, 0x29, 0xb9, 0xf4, 0xfc, 0xfc, 0xf4, 0x9c, 0x54, 0x88, 0xc2, 0xa4, 0xd2, 0x34, 0xfd,
	0xf2, 0xa2, 0xc4, 0x82, 0x82, 0xd4, 0x22, 0xa8, 0x6a, 0x23, 0x6f, 0x2e, 0x66, 0xc7, 0x00, 0x4f,
	0x21, 0x17, 0x2e, 0x26, 0x97, 0x7c, 0x21, 0x69, 0x3d, 0x88, 0x6a, 0x3d, 0x98, 0x6a, 0x3d, 0xa7,
	0xca, 0x92, 0xd4, 0xe2, 0xb0, 0xc4, 0x9c, 0xd2, 0x54, 0x29, 0x7c, 0x92, 0x4a, 0x0c, 0x1a, 0x8c,
	0x06, 0x8c, 0x49, 0x6c, 0x60, 0x29, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x44, 0x68, 0x7e,
	0x7b, 0x9f, 0x00, 0x00, 0x00,
}
